// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'firebase_options.dart';


// ...

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADq1NZTCfHH9rQkS1HF4N6M5Jf9adeir0',
    appId: '1:391545280397:web:a36814f0022f9d21310fc4',
    messagingSenderId: '391545280397',
    projectId: 'facebook-85010',
    authDomain: 'facebook-85010.firebaseapp.com',
    storageBucket: 'facebook-85010.firebasestorage.app',
    measurementId: 'G-1SSCFCDJVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9eUyJ-iJwdNCQ0GQeIK01D4r1OI87988',
    appId: '1:391545280397:android:e6ea17a0ba5ffe67310fc4',
    messagingSenderId: '391545280397',
    projectId: 'facebook-85010',
    storageBucket: 'facebook-85010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHMGktGLkLoUZFZQmb-AKm0lH7saT2QQ',
    appId: '1:391545280397:ios:9340fac9345f40db310fc4',
    messagingSenderId: '391545280397',
    projectId: 'facebook-85010',
    storageBucket: 'facebook-85010.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRHMGktGLkLoUZFZQmb-AKm0lH7saT2QQ',
    appId: '1:391545280397:ios:9340fac9345f40db310fc4',
    messagingSenderId: '391545280397',
    projectId: 'facebook-85010',
    storageBucket: 'facebook-85010.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADq1NZTCfHH9rQkS1HF4N6M5Jf9adeir0',
    appId: '1:391545280397:web:f9a18725b2e3d8d4310fc4',
    messagingSenderId: '391545280397',
    projectId: 'facebook-85010',
    authDomain: 'facebook-85010.firebaseapp.com',
    storageBucket: 'facebook-85010.firebasestorage.app',
    measurementId: 'G-4F7MZ8FV9B',
  );
}
